### ISSUE TITLE
 Information Update - First Issue

### ISSUE THREAD

**Issue by KaganCanSit** [yakuter/go-developer-list#77]
199. satırda adım ve bilgilerim yer alıyor. Fakat bu bilgiler güncel değil ve eksik. Bu bilgilerin sıralı olarak aşağıdaki gibi güncellenmesini rica ediyorum.

Kağan Can Şit
Üniversite Öğrencisi (Staj Arayışında) 
https://github.com/KaganCanSit || https://www.linkedin.com/in/kagancansit/ || https://twitter.com/kagancansit || CV >> https://github.com/KaganCanSit/KaganCanSit/blob/master/Open%20CV.pdf
Go dilinde başlangıç. C,C++,C#,SQL üzerine projeler. Web(Html,CSS,Node.js,MVC Mimarisi) ve Java üzerine yeni deneyim.

Not: İlk issue isteğimi burada yapmak istedim. Tekrardan  teşekkürler bilginizi benimle  paylaştığınız için.

**Comment by yakuter** [comment]
Kaancım selam. Bu şekilde değil de projeyi forklayıp, istediğin değişikliği yapıp PR açarsan ona göre merge'leyebilirim. Yani standart açık kaynak proje katkı yolunu izliyoruz.

**Comment by KaganCanSit** [comment]
Tamamdır. Hemen ilgileniyorum.
